const en = {
  translation: {
    nav: { home:'Home', families:'Families', patients:'Patients', profile:'Profile', back:'← Back', backToFamilies:'← Back to Families' },
    home: { totalPatients:'Total Patients', missedVisits:'Missed Visits', upcomingVaccines:'Upcoming Vaccines', families:'Families', riskGroups:'Risk Groups', reminders:'Reminders', overdue:'Overdue' },
    families: { title:'Families', add:'+ Add', addTitle:'Add Family', headOfFamily:'Head of Family', address:'Address', phone:'Phone', noFamilies:'No families yet', members:'Members', addMember:'+ Add Member', cancel:'Cancel', save:'Save', edit:'Edit', delete:'Delete', confirmDelete:'Delete family?', noMembers:'No members yet', updated:'Updated!' },
    patients: { title:'Patients', add:'+ Add', addTitle:'Add Patient', search:'Search by name or passport...', allRisk:'All Risk', allVisits:'All Visits', found:'patient(s) found', noPatients:'No patients found', fullName:'Full Name', passport:'Passport ID', birthDate:'Date of Birth', bloodGroup:'Blood Group', riskCategory:'Risk Category', height:'Height (cm)', weight:'Weight (kg)', bp:'Blood Pressure', notes:'Notes', family:'Family', noFamily:'— No family —', edit:'Edit', delete:'Delete', confirmDelete:'Delete this patient?', save:'Save', cancel:'Cancel', update:'Update', saving:'Saving...', saved:'Saved!', updated:'Updated!', added:'Patient added!', select:'Select', addNotes:'Additional notes...' },
    visits: { title:'Visits', add:'+ Visit', addTitle:'Add Visit', visitDate:'Visit Date', nextVisitDate:'Next Visit Date', status:'Status', pending:'⏳ Pending', completed:'✅ Completed', missed:'⚠️ Missed', noVisits:'No visits yet', overdue:'overdue', next:'Next', save:'Save', cancel:'Cancel', added:'Added' },
    history: { title:'History', add:'+ Record', addTitle:'Add Visit Record', date:'Date', diagnosis:'Diagnosis', medication:'Medication', notes:'Notes', noHistory:'No history yet', save:'Save', cancel:'Cancel', added:'Added' },
    vaccines: { title:'Vaccines', add:'+ Vaccine', addTitle:'Add Vaccination', name:'Vaccine Name', dateGiven:'Date Given', nextDate:'Next Date', noVaccines:'No vaccines recorded', overdue:'Overdue', upcoming:'Upcoming', given:'Given', nameRequired:'Name required', save:'Save', cancel:'Cancel', added:'Added' },
    meds: { title:'Medications', add:'+ Medication', addTitle:'Add Medication', name:'Medicine Name', quantity:'Quantity', timesDay:'Times/day', days:'Days', dateGiven:'Date Given', noMeds:'No medications', nameRequired:'Name required', save:'Save', cancel:'Cancel', added:'Added' },
    images: { title:'Images', caption:'Caption (optional)', upload:'📷 Upload Image', noImages:'No images', captionPlaceholder:'e.g. Wound progress' },
    profile: { title:'Profile', settings:'Settings', name:'Name', phone:'Phone', language:'Language', theme:'Theme', themeLight:'☀️ Light', themeDark:'🌙 Dark', saveChanges:'Save Changes', saving:'Saving...', saved:'Saved!', credentials:'Credentials', change:'Change', cancel:'Cancel', currentPassword:'Current Password', newLogin:'New Login (optional)', newPassword:'New Password (optional)', update:'Update', updated:'Updated!', currentPasswordRequired:'Current password required', export:'Export', exportSub:'Excel / CSV', import:'Import', importSub:'From Excel', signOut:'Sign Out', photoUpdated:'Photo updated!', uploadFailed:'Upload failed' },
    export: { title:'Export', format:'Format', filters:'Filters', searchName:'Search by name...', searchAddress:'Search by address...', searchVaccine:'Search by vaccine...', allRisk:'All Risk', allVisit:'All Visits', selectAll:'Select All', selected:'selected', allWillExport:'All will export', btn:'📤 Export', back:'← Back', success:'patients exported!' },
    import: { title:'Import', back:'← Back', formatTitle:'📋 Excel file format:', formatCols:'Columns in any order', formatRequired:'Required: Full Name, Passport ID', formatOptional:'Optional: Family, DOB, Blood Group, Risk', formatTypes:'Formats: .xlsx · .xls · .csv', tapToSelect:'Tap to select file', rowsFound:'rows found. Review mapping:', importNow:'🚀 Import Now', importing:'Importing...', analyzing:'Analyzing...', done:'Done', complete:'✓ Import complete!', analysisFailed:'Analysis failed', importFailed:'Import failed', createdFamilies:'🏠 Families', newPatients:'👥 New Patients', updatedP:'✏️ Updated', skipped:'⚠️ Skipped' },
    tabs: { info:'info', history:'history', visits:'visits', vaccines:'vaccines', meds:'meds', images:'images' },
    risk: { pregnant:'Pregnant', child05:'Child 0–5', chronic:'Chronic', disabled:'Disabled', normal:'Normal' },
    common: { loading:'Loading...', error:'Error', failedLoad:'Failed to load', deleted:'Deleted', nameRequired:'Name required', members:'member(s)', notMapped:'— not mapped —' }
  }
};
export default en;
