const ru = {
  translation: {
    nav: { home:'Главная', families:'Семьи', patients:'Пациенты', profile:'Профиль', back:'← Назад', backToFamilies:'← К семьям' },
    home: { totalPatients:'Всего пациентов', missedVisits:'Пропущенные визиты', upcomingVaccines:'Предстоящие прививки', families:'Семьи', riskGroups:'Группы риска', reminders:'Напоминания', overdue:'Просрочено' },
    families: { title:'Семьи', add:'+ Добавить', addTitle:'Добавить семью', headOfFamily:'Глава семьи', address:'Адрес', phone:'Телефон', noFamilies:'Семей пока нет', members:'Члены', addMember:'+ Добавить члена', cancel:'Отмена', save:'Сохранить', edit:'Редактировать', delete:'Удалить', confirmDelete:'Удалить семью?', noMembers:'Членов пока нет', updated:'Обновлено!' },
    patients: { title:'Пациенты', add:'+ Добавить', addTitle:'Добавить пациента', search:'Поиск по имени или паспорту...', allRisk:'Все риски', allVisits:'Все визиты', found:'пациент(ов) найдено', noPatients:'Пациенты не найдены', fullName:'ФИО', passport:'Паспорт ID', birthDate:'Дата рождения', bloodGroup:'Группа крови', riskCategory:'Категория риска', height:'Рост (см)', weight:'Вес (кг)', bp:'Давление', notes:'Заметки', family:'Семья', noFamily:'— Без семьи —', edit:'Редактировать', delete:'Удалить', confirmDelete:'Удалить пациента?', save:'Сохранить', cancel:'Отмена', update:'Обновить', saving:'Сохранение...', saved:'Сохранено!', updated:'Обновлено!', added:'Пациент добавлен!', select:'Выбрать', addNotes:'Дополнительные заметки...' },
    visits: { title:'Визиты', add:'+ Визит', addTitle:'Добавить визит', visitDate:'Дата визита', nextVisitDate:'Следующий визит', status:'Статус', pending:'⏳ Ожидается', completed:'✅ Завершён', missed:'⚠️ Пропущен', noVisits:'Визитов нет', overdue:'просрочено', next:'Следующий', save:'Сохранить', cancel:'Отмена', added:'Добавлено' },
    history: { title:'История', add:'+ Запись', addTitle:'Добавить запись', date:'Дата', diagnosis:'Диагноз', medication:'Лекарство', notes:'Заметки', noHistory:'Истории нет', save:'Сохранить', cancel:'Отмена', added:'Добавлено' },
    vaccines: { title:'Прививки', add:'+ Прививка', addTitle:'Добавить прививку', name:'Название', dateGiven:'Дата введения', nextDate:'Следующая дата', noVaccines:'Прививок нет', overdue:'Просрочено', upcoming:'Предстоящие', given:'Сделано', nameRequired:'Нужно название', save:'Сохранить', cancel:'Отмена', added:'Добавлено' },
    meds: { title:'Лекарства', add:'+ Лекарство', addTitle:'Добавить лекарство', name:'Название', quantity:'Количество', timesDay:'Раз в день', days:'Дней', dateGiven:'Дата выдачи', noMeds:'Лекарств нет', nameRequired:'Нужно название', save:'Сохранить', cancel:'Отмена', added:'Добавлено' },
    images: { title:'Снимки', caption:'Подпись (необязательно)', upload:'📷 Загрузить фото', noImages:'Снимков нет', captionPlaceholder:'Напр. Прогресс раны' },
    profile: { title:'Профиль', settings:'Настройки', name:'Имя', phone:'Телефон', language:'Язык', theme:'Тема', themeLight:'☀️ Светлая', themeDark:'🌙 Тёмная', saveChanges:'Сохранить изменения', saving:'Сохранение...', saved:'Сохранено!', credentials:'Данные входа', change:'Изменить', cancel:'Отмена', currentPassword:'Текущий пароль', newLogin:'Новый логин (необязательно)', newPassword:'Новый пароль (необязательно)', update:'Обновить', updated:'Обновлено!', currentPasswordRequired:'Нужен текущий пароль', export:'Экспорт', exportSub:'Excel / CSV', import:'Импорт', importSub:'Из Excel', signOut:'Выйти', photoUpdated:'Фото обновлено!', uploadFailed:'Ошибка загрузки' },
    export: { title:'Экспорт', format:'Формат', filters:'Фильтры', searchName:'Поиск по имени...', searchAddress:'Поиск по адресу...', searchVaccine:'Поиск по прививке...', allRisk:'Все риски', allVisit:'Все визиты', selectAll:'Выбрать все', selected:'выбрано', allWillExport:'Все будут экспортированы', btn:'📤 Экспорт', back:'← Назад', success:'пациент(ов) экспортировано!' },
    import: { title:'Импорт', back:'← Назад', formatTitle:'📋 Формат Excel файла:', formatCols:'Столбцы в любом порядке', formatRequired:'Обязательно: ФИО, Паспорт ID', formatOptional:'Необязательно: Семья, Дата рождения, Группа крови, Риск', formatTypes:'Форматы: .xlsx · .xls · .csv', tapToSelect:'Нажмите для выбора файла', rowsFound:'строк найдено. Проверьте маппинг:', importNow:'🚀 Импортировать', importing:'Импортируется...', analyzing:'Анализируется...', done:'Готово', complete:'✓ Импорт завершён!', analysisFailed:'Ошибка анализа', importFailed:'Ошибка импорта', createdFamilies:'🏠 Семей', newPatients:'👥 Новых пациентов', updatedP:'✏️ Обновлено', skipped:'⚠️ Пропущено' },
    tabs: { info:'инфо', history:'история', visits:'визиты', vaccines:'прививки', meds:'лекарства', images:'снимки' },
    risk: { pregnant:'Беременные', child05:'Дети 0-5', chronic:'Хронические', disabled:'Инвалиды', normal:'Обычные' },
    common: { loading:'Загрузка...', error:'Ошибка', failedLoad:'Не удалось загрузить', deleted:'Удалено', nameRequired:'Нужно имя', members:'чел.', notMapped:'— не маппировано —' }
  }
};
export default ru;
