const uz = {
  translation: {
    nav: { home:'Bosh sahifa', families:'Oilalar', patients:'Bemorlar', profile:'Profil', back:'← Orqaga', backToFamilies:'← Oilalarga qaytish' },
    home: { totalPatients:'Jami bemorlar', missedVisits:'O\'tkazilgan tashriflar', upcomingVaccines:'Yaqin emlashlar', families:'Oilalar', riskGroups:'Xavf guruhlari', reminders:'Eslatmalar', overdue:'Muddati o\'tgan' },
    families: { title:'Oilalar', add:'+ Qo\'shish', addTitle:'Oila qo\'shish', headOfFamily:'Oila boshlig\'i', address:'Manzil', phone:'Telefon', noFamilies:'Hali oilalar yo\'q', members:'A\'zolar', addMember:'+ A\'zo qo\'shish', cancel:'Bekor qilish', save:'Saqlash', edit:'Tahrirlash', delete:'O\'chirish', confirmDelete:'Oilani o\'chirishni tasdiqlaysizmi?', noMembers:'Hali a\'zolar yo\'q', updated:'Yangilandi!' },
    patients: { title:'Bemorlar', add:'+ Qo\'shish', addTitle:'Bemor qo\'shish', search:'Ism yoki pasport bo\'yicha...', allRisk:'Barcha xavf', allVisits:'Barcha tashriflar', found:'ta bemor topildi', noPatients:'Bemorlar topilmadi', fullName:'To\'liq ism', passport:'Pasport ID', birthDate:'Tug\'ilgan sana', bloodGroup:'Qon guruhi', riskCategory:'Xavf toifasi', height:'Bo\'y (sm)', weight:'Vazn (kg)', bp:'Qon bosimi', notes:'Izohlar', family:'Oila', noFamily:'— Oilasiz —', edit:'Tahrirlash', delete:'O\'chirish', confirmDelete:'Bu bemorni o\'chirishni tasdiqlaysizmi?', save:'Saqlash', cancel:'Bekor qilish', update:'Yangilash', saving:'Saqlanmoqda...', saved:'Saqlandi!', updated:'Yangilandi!', added:'Bemor qo\'shildi!', select:'Tanlash', addNotes:'Qo\'shimcha izohlar...' },
    visits: { title:'Tashriflar', add:'+ Tashrif', addTitle:'Tashrif qo\'shish', visitDate:'Tashrif sanasi', nextVisitDate:'Keyingi tashrif', status:'Holat', pending:'⏳ Kutilmoqda', completed:'✅ Bajarildi', missed:'⚠️ O\'tkazildi', noVisits:'Tashriflar yo\'q', overdue:'muddati o\'tgan', next:'Keyingi', save:'Saqlash', cancel:'Bekor qilish', added:'Qo\'shildi' },
    history: { title:'Tarix', add:'+ Yozuv', addTitle:'Yozuv qo\'shish', date:'Sana', diagnosis:'Tashxis', medication:'Dori', notes:'Izohlar', noHistory:'Tarix yo\'q', save:'Saqlash', cancel:'Bekor qilish', added:'Qo\'shildi' },
    vaccines: { title:'Emlashlar', add:'+ Emlash', addTitle:'Emlash qo\'shish', name:'Emlash nomi', dateGiven:'Berilgan sana', nextDate:'Keyingi sana', noVaccines:'Emlashlar yo\'q', overdue:'Muddati o\'tgan', upcoming:'Yaqinlashmoqda', given:'Berilgan', nameRequired:'Nom kerak', save:'Saqlash', cancel:'Bekor qilish', added:'Qo\'shildi' },
    meds: { title:'Dorilar', add:'+ Dori', addTitle:'Dori qo\'shish', name:'Dori nomi', quantity:'Miqdor', timesDay:'Kuniga marta', days:'Kun', dateGiven:'Berilgan sana', noMeds:'Dorilar yo\'q', nameRequired:'Nom kerak', save:'Saqlash', cancel:'Bekor qilish', added:'Qo\'shildi' },
    images: { title:'Rasmlar', caption:'Izoh (ixtiyoriy)', upload:'📷 Rasm yuklash', noImages:'Rasmlar yo\'q', captionPlaceholder:'Masalan: Yara holati' },
    profile: { title:'Profil', settings:'Sozlamalar', name:'Ism', phone:'Telefon', language:'Til', theme:'Mavzu', themeLight:'☀️ Yorug\'', themeDark:'🌙 Qorong\'i', saveChanges:'O\'zgarishlarni saqlash', saving:'Saqlanmoqda...', saved:'Saqlandi!', credentials:'Kirish ma\'lumotlari', change:'O\'zgartirish', cancel:'Bekor qilish', currentPassword:'Joriy parol', newLogin:'Yangi login (ixtiyoriy)', newPassword:'Yangi parol (ixtiyoriy)', update:'Yangilash', updated:'Yangilandi!', currentPasswordRequired:'Joriy parol kerak', export:'Eksport', exportSub:'Excel / CSV', import:'Import', importSub:'Exceldan', signOut:'Chiqish', photoUpdated:'Rasm yangilandi!', uploadFailed:'Yuklash muvaffaqiyatsiz' },
    export: { title:'Eksport', format:'Format', filters:'Filtrlar', searchName:'Ism bo\'yicha qidirish...', searchAddress:'Manzil bo\'yicha...', searchVaccine:'Emlash nomi bo\'yicha...', allRisk:'Barcha xavf', allVisit:'Barcha tashriflar', selectAll:'Hammasini tanlash', selected:'tanlangan', allWillExport:'Hammasi eksport qilinadi', btn:'📤 Eksport', back:'← Orqaga', success:'ta bemor eksport qilindi!' },
    import: { title:'Import', back:'← Orqaga', formatTitle:'📋 Excel fayl formati:', formatCols:'Ustunlar istalgan tartibda', formatRequired:'Majburiy: To\'liq ism, Pasport ID', formatOptional:'Ixtiyoriy: Oila, Tug\'ilgan sana, Qon guruhi, Xavf', formatTypes:'Formatlar: .xlsx · .xls · .csv', tapToSelect:'Fayl tanlash uchun bosing', rowsFound:'qator topildi. Xaritani tekshiring:', importNow:'🚀 Import qilish', importing:'Import qilinmoqda...', analyzing:'Tahlil qilinmoqda...', done:'Tayyor', complete:'✓ Import bajarildi!', analysisFailed:'Tahlil xatosi', importFailed:'Import xatosi', createdFamilies:'🏠 Oilalar', newPatients:'👥 Yangi bemorlar', updatedP:'✏️ Yangilangan', skipped:'⚠️ O\'tkazilgan' },
    tabs: { info:'ma\'lumot', history:'tarix', visits:'tashriflar', vaccines:'emlashlar', meds:'dorilar', images:'rasmlar' },
    risk: { pregnant:'Homilador', child05:'Bola 0-5', chronic:'Surunkali', disabled:'Nogironlar', normal:'Oddiy' },
    common: { loading:'Yuklanmoqda...', error:'Xatolik', failedLoad:'Yuklab bo\'lmadi', deleted:'O\'chirildi', nameRequired:'Ism kerak', members:'ta a\'zo', notMapped:'— xaritada yo\'q —' }
  }
};
export default uz;
